#!/bin/bash

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -z "$SERVER" ]; then
    echo "SERVER is not set"
    exit 1
fi

run() {
    echo "%%%%%%%%%%%%%%%%%% $1 %%%%%%%%%%%%%%%%%%"
    echo 1 > /proc/netmem_stats/reset
    $1 `#> /dev/null 2>&1`; sleep 1
    bash $THIS_DIR/../utils/sorted-per-site-stats.sh
}

# Interface "lo" is not ARPable
run "arping -c 1 localhost"
# run "arping -c 5 localhost"
# run "arping -c 10 localhost"
run "arping -c 1 $SERVER"
run "arping -c 5 $SERVER"
run "arping -c 10 $SERVER"
