#!/bin/bash

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

run() {
    echo "%%%%%%%%%%%%%%%%%% $1 | nc -q 0 10.0.2.2 10000 %%%%%%%%%%%%%%%%%%"
    echo 1 > /proc/netmem_stats/reset
    $1 | nc -q 0 10.0.2.2 10000 > /dev/null `#2>&1`; sleep 1
    bash $THIS_DIR/../utils/sorted-per-site-stats.sh
}

run "dd if=/dev/random bs=1 count=1"
run "dd if=/dev/random bs=1k count=1"
run "dd if=/dev/random bs=1M count=1"
run "dd if=/dev/random bs=1M count=20"
