#!/bin/bash

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

run() {
    echo "%%%%%%%%%%%%%%%%%% $1 %%%%%%%%%%%%%%%%%%"
    echo 1 > /proc/netmem_stats/reset
    $1 `#> /dev/null 2>&1`; sleep 1
    bash $THIS_DIR/../utils/sorted-per-site-stats.sh
}

run "iperf3 -c 10.0.2.2 -t 3"
run "iperf3 -c localhost -t 3"
run "iperf3 -c 10.0.2.2 -t 3 -l 1K"
run "iperf3 -c 10.0.2.2 -t 3 -l 1K -N"
run "iperf3 -c 10.0.2.2 -t 3 -l 128K"
run "iperf3 -c 10.0.2.2 -n 4M"
run "iperf3 -c 10.0.2.2 -t 3 -R"
run "iperf3 -c 10.0.2.2 -u -b 10M -l 512 -t 3"
run "iperf3 -c 10.0.2.2 -u -b 20M -l 1400 -t 3"
run "iperf3 -c 10.0.2.2 -6 -t 3"
run "iperf3 -c 10.0.2.2 -6 -u -b 10M -l 512 -t 3"
run "iperf3 -c 10.0.2.2 -P 4 -t 3"
run "iperf3 -c 10.0.2.2 -t 3 -S 0xb8"
run "iperf3 -c 10.0.2.2 -t 3 -Z"
