#!/bin/bash

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

run() {
    echo "%%%%%%%%%%%%%%%%%% $1 %%%%%%%%%%%%%%%%%%"
    echo 1 > /proc/netmem_stats/reset
    $1 > /dev/null 2>&1; sleep 1
    bash $THIS_DIR/../utils/sorted-per-site-stats.sh
}

run "ping -4 -c 1 -s 86 localhost"
run "ping -4 -c 1 -s 4096 localhost"
run "ping -4 -c 1 -s 40960 localhost"
run "ping -4 -c 5 -s 4096 localhost"
run "ping -c 1 -s 86 10.0.2.2"
run "ping -c 1 -s 87 10.0.2.2"
run "ping -c 1 -s 1600 10.0.2.2"
