#!/bin/bash

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

run() {
    echo "%%%%%%%%%%%%%%%%%% $1 %%%%%%%%%%%%%%%%%%"
    echo 1 > /proc/netmem_stats/reset
    $1 `#> /dev/null 2>&1`; sleep 1
    bash $THIS_DIR/../utils/sorted-per-site-stats.sh
}

run "wrk -t12 -c400 -d30s http://10.0.2.2/index.html"
