#!/bin/bash

THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -z "$SERVER" ]; then
    echo "SERVER is not set"
    exit 1
fi

run() {
    echo "%%%%%%%%%%%%%%%%%% $1 %%%%%%%%%%%%%%%%%%"
    echo 1 > /proc/netmem_stats/reset
    $1 `#> /dev/null 2>&1`; sleep 1
    bash $THIS_DIR/../utils/sorted-per-site-stats.sh
}

run "wrk -t12 -c400 -d30s http://$SERVER/index.html"
